"""Build a single self-contained HTML dashboard from a compiled circuit.

The dashboard embeds the pulse-timeline SVG, the control-cost metrics, the
Markdown cost report, and previews of the instruction/pattern memory — an "app"
view you can open in any browser, with no third-party dependencies.
"""

from __future__ import annotations

import html
from typing import List

from .pipeline import CompileResult
from .report import render_report
from .visualize import render_svg


def _table(headers: List[str], rows: List[List[str]]) -> str:
    head = "".join(f"<th>{html.escape(str(h))}</th>" for h in headers)
    body = "".join(
        "<tr>" + "".join(f"<td>{html.escape(str(c))}</td>" for c in r) + "</tr>"
        for r in rows)
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


def _md_to_html(md: str) -> str:
    """Very small Markdown -> HTML (headings, tables, lists, paragraphs)."""
    out: List[str] = []
    in_table = False
    for line in md.splitlines():
        s = line.rstrip()
        if s.startswith("|") and "|" in s[1:]:
            cells = [c.strip() for c in s.strip("|").split("|")]
            if set("".join(cells)) <= set("-: "):   # separator row
                continue
            if not in_table:
                out.append("<table>"); in_table = True
            tag = "td"
            out.append("<tr>" + "".join(f"<{tag}>{html.escape(c)}</{tag}>"
                                        for c in cells) + "</tr>")
            continue
        if in_table:
            out.append("</table>"); in_table = False
        if s.startswith("### "):
            out.append(f"<h3>{html.escape(s[4:])}</h3>")
        elif s.startswith("## "):
            out.append(f"<h2>{html.escape(s[3:])}</h2>")
        elif s.startswith("# "):
            out.append(f"<h1>{html.escape(s[2:])}</h1>")
        elif s.startswith("- "):
            out.append(f"<li>{html.escape(s[2:])}</li>")
        elif s:
            out.append(f"<p>{html.escape(s)}</p>")
    if in_table:
        out.append("</table>")
    return "\n".join(out)


_CSS = """
body{font-family:system-ui,Segoe UI,Roboto,sans-serif;margin:0;background:#f6f7f9;color:#222}
header{background:#1f2933;color:#fff;padding:18px 28px}
header h1{margin:0;font-size:20px}
header p{margin:4px 0 0;color:#9aa5b1;font-size:13px}
main{max-width:980px;margin:0 auto;padding:24px}
section{background:#fff;border:1px solid #e4e7eb;border-radius:8px;padding:18px 22px;margin:18px 0}
h2{font-size:16px;border-bottom:1px solid #eee;padding-bottom:6px}
table{border-collapse:collapse;font-size:13px;margin:8px 0}
th,td{border:1px solid #e4e7eb;padding:4px 10px;text-align:left}
th{background:#f0f3f6}
svg{max-width:100%;height:auto}
.metrics td:last-child{font-variant-numeric:tabular-nums;text-align:right}
.foot{color:#9aa5b1;font-size:12px;text-align:center;margin:24px 0}
"""


def build_dashboard(result: CompileResult, title: str = "circuit") -> str:
    m = result.metrics
    mem = result.memory
    metrics_rows = [[k, v] for k, v in m.as_dict().items()]
    pat_rows = [[r["pattern_id"], r["output"], r["sequencer"], r["dac_code"],
                 r["width_samples"], r["exchange_area"]] for r in mem.pattern_memory[:12]]
    instr_rows = [[r["addr"], r["sequencer"], r["output"], r["op"], r["pattern_id"],
                   r["t_start_samples"], r["width_samples"], r["gate"]]
                  for r in mem.instruction_memory[:12]]
    svg = render_svg(result.schedule, f"EO pulse timeline — {title}")
    report_html = _md_to_html(render_report(m, mem, result.hardware,
                                            title=f"EO Pulse Control IR — {title}"))

    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>EO Pulse Control IR — {html.escape(title)}</title><style>{_CSS}</style></head>
<body>
<header><h1>EO Pulse Control IR</h1>
<p>Exchange-only spin-qubit control dashboard · circuit: {html.escape(title)}</p></header>
<main>
<section><h2>Pulse timeline</h2>{svg}</section>
<section class="metrics"><h2>Control-cost metrics</h2>{_table(["metric", "value"], metrics_rows)}</section>
<section><h2>Cost report</h2>{report_html}</section>
<section><h2>Pattern memory (preview)</h2>
{_table(["pattern_id", "output", "seq", "dac_code", "width", "area"], pat_rows)}</section>
<section><h2>Instruction memory (preview)</h2>
{_table(["addr", "seq", "output", "op", "pattern", "t_start", "width", "gate"], instr_rows)}</section>
<p class="foot">generated by <code>eo dashboard</code> · eo-pulse-ir</p>
</main></body></html>"""
