"""Lie-algebra / controllability tools for the exchange-only control system.

Exchange-only pulse control is a *piecewise-constant* (switched bilinear),
right-invariant control system on SU(2**n):

    dU/dt = -i H(t) U,     H(t) = H_drift + J · G_{edge(t)}

where the switching signal selects which nearest-neighbour exchange generator
G_edge = S_i·S_j is active, J is the (square) amplitude, and H_drift is the
always-on Zeeman field.  The set of gates reachable by *some* control word is the
connected Lie group whose algebra is generated, under commutation, by the control
Hamiltonians (Lie-algebra rank condition / Chow's theorem).

This module computes that generated Lie algebra numerically (dimension + basis)
in a fixed total-S_z sector (exchange and Zeeman both conserve S_z, keeping the
matrices small), and tests whether the algebra couples the logical subspace to
the leakage subspace.
"""

from __future__ import annotations

from typing import List, Sequence, Tuple

import numpy as np


def sector_indices(n: int, n_down: int) -> List[int]:
    """Computational-basis indices of the total-S_z sector with ``n_down`` downs."""
    return [i for i in range(1 << n) if bin(i).count("1") == n_down]


def restrict(M: np.ndarray, idx: Sequence[int]) -> np.ndarray:
    idx = np.asarray(idx)
    return M[np.ix_(idx, idx)]


def traceless(M: np.ndarray) -> np.ndarray:
    return M - np.trace(M) / M.shape[0] * np.eye(M.shape[0])


def as_generator(H: np.ndarray) -> np.ndarray:
    """Hermitian H -> anti-Hermitian generator iH (an element of u(d))."""
    return 1j * H


def lie_closure(generators: Sequence[np.ndarray], tol: float = 1e-8,
                cap: int = 2000) -> Tuple[int, List[np.ndarray]]:
    """Dimension and a basis of the real Lie algebra generated by ``generators``.

    ``generators`` are anti-Hermitian matrices.  Iteratively adds commutators that
    are linearly independent (over the reals) of the current span, until closure
    or ``cap`` is hit.
    """
    basis: List[np.ndarray] = []
    Q = None  # orthonormal rows of flattened (real) basis vectors

    def _add(M: np.ndarray) -> bool:
        nonlocal Q
        v = np.concatenate([M.real.ravel(), M.imag.ravel()]).astype(float)
        if Q is not None:
            v = v - Q.T @ (Q @ v)
        nrm = np.linalg.norm(v)
        if nrm < tol:
            return False
        v /= nrm
        Q = v[None, :] if Q is None else np.vstack([Q, v])
        basis.append(M)
        return True

    for g in generators:
        _add(g)
    i = 0
    while i < len(basis):
        for j in range(i + 1):
            C = basis[i] @ basis[j] - basis[j] @ basis[i]
            _add(C)
            if len(basis) >= cap:
                return len(basis), basis
        i += 1
    return len(basis), basis


def subspace_coupling(basis: Sequence[np.ndarray], A: np.ndarray,
                      B: np.ndarray) -> float:
    """Max |<b| X |a>| over algebra elements X and columns a of A, b of B.

    A, B are isometries (columns = orthonormal states) spanning two subspaces; a
    nonzero value means the algebra can drive population between them.
    """
    m = 0.0
    for X in basis:
        C = B.conj().T @ X @ A
        m = max(m, float(np.max(np.abs(C))) if C.size else 0.0)
    return m
